titoli_funzionanti <- c("ACHI", "AMAG", "AAPL", "BBSI", "BBY",  "HRB", "BPT",  "BKE",  "CPLA", "CSCO", "ENTA", "GME",  "HPQ", "IQNT", "IDCC", "KBR",  "KFY",  "LEA",  "LDOS", "MED",  "MPAA", "MSGN", "NATH", "NSR",  "PBI",  "SPOK", "STRA", "SYNT", "TDC",  "UIS",  "UTHR", "USNA", "VIAB", "WNC",  "WILN")

titoli_completi_30 <- c("ACHI", "AAPL", "AGX", "AVID", "BBSI", "BPT", "BKE",  "CPLA", "CHKE", "CSCO", "ENTA", "GME",  "HPQ", "IDCC", "KFY", "MBUU", "MCFT", "MSGN", "NHTC", "NSR", "NRT", "OUTR", "PDLI", "SSNI", "TDC", "UIS", "UTHR", "VIAB", "WILN")

my_ups <- c("HRB","CPLA")

my_downs <- c("ACHI","AAPL","AGX")

#TITOLI CHARACTER

#ACHI AMAG AMCX AAPL AGTC AGX AVID AWRE BBSI BGSF HRB BPT CA CHKE CSCO DHX ENTA FPRX GME GILD GHC HSII HPQ IDCC IRMD MBUU MCFT MCK MDCA MPAA MSGN NHTC NSR PBI RPXC SSNI SWHC SPOK RGR SYNT TGNA TDC TRNC UIS UTHR USNA VEC VIAB

